Update basic_indicator.py
webcat051/Trading-Bot pull request #3
Opened 2022-10-30 09:08 UTC by tsv19su254052

Подправил

2022-11-02 11:33 UTC, NewYongJun commented
Hello.

2022-11-02 11:34 UTC, webcat051 commented
Hello.

On Wed, Nov 2, 2022 at 4:33 AM NewYongJun ***@***.***> wrote:

> Hello.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/webcat051/Trading-Bot/pull/3#issuecomment-1300157184>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXQVYXRYC2QB3CL6LIXFEO3WGJGRBANCNFSM6AAAAAARSGBI7I>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-11-08 09:36 UTC, webcat051 requested changes
Hello.
Thanks for your use my repository  and request push.
I did check all code.
Could you please change about my request?
Thanks.

2022-11-08 09:36 UTC, webcat051 commented on trading_bot/indicators/basic_indicator.py
> +        BasicIndicator.__init__(self,
why did you put Enter on this line.
Could you change?

2022-11-08 09:36 UTC, webcat051 commented on trading_bot/indicators/basic_indicator.py
> +        BasicIndicator.__init__(self,
and Could you please change this line?

2022-11-08 09:41 UTC, merged